resources:
  repositories:
  - repository: self
    type: git
    ref: main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: NodeTool@0
    displayName: Use Node 20.x
    inputs:
      versionSpec: 20.x
  - task: Npm@1
    displayName: npm ci
    inputs:
      command: ci
      verbose: false
  - task: mochawesome 
  - script: npx cypress run
    displayName: 'Run Cypress tests with Mochawesome'
  - task: PublishPipelineArtifact@1
    displayName: Publish Pipeline Artifact
    inputs:
      artifactName: Cypress Build Pipeline
  - task: PublishPipelineArtifact@2
  inputs:
    targetPath: 'cypress/reports/mochawesome-report'
    artifact: 'mochawesome-report'
    publishLocation: 'pipeline'
    displayName: 'Publish Mochawesome HTML report'
...
