resources:
  repositories:
  - repository: self
    type: git
    ref: main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: NodeTool@0
    displayName: Use Node 20.x
    inputs:
      versionSpec: 20.x
  - task: Npm@1
    displayName: npm ci
    inputs:
      command: ci
      verbose: false

  - script: npx cypress run
    displayName: 'Run cypress tests' 
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Mochawesome HTML report'
    inputs:
      targetPath: 'cypress/reports/mochawesome-report'   # exact path to your report folder
      artifact: 'mochawesome-report'
      publishLocation: 'pipeline'
